# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/media/guillaume/Data/Guillaume Coiffier/Documents/C++/Raytracer"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/media/guillaume/Data/Guillaume Coiffier/Documents/C++/Raytracer"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/guillaume/Data/Guillaume Coiffier/Documents/C++/Raytracer/CMakeFiles" "/media/guillaume/Data/Guillaume Coiffier/Documents/C++/Raytracer/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/guillaume/Data/Guillaume Coiffier/Documents/C++/Raytracer/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Raytracer

# Build rule for target.
Raytracer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Raytracer
.PHONY : Raytracer

# fast build rule for target.
Raytracer/fast:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/build
.PHONY : Raytracer/fast

src/CollisionManager.o: src/CollisionManager.cpp.o

.PHONY : src/CollisionManager.o

# target to build an object file
src/CollisionManager.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/CollisionManager.cpp.o
.PHONY : src/CollisionManager.cpp.o

src/CollisionManager.i: src/CollisionManager.cpp.i

.PHONY : src/CollisionManager.i

# target to preprocess a source file
src/CollisionManager.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/CollisionManager.cpp.i
.PHONY : src/CollisionManager.cpp.i

src/CollisionManager.s: src/CollisionManager.cpp.s

.PHONY : src/CollisionManager.s

# target to generate assembly for a file
src/CollisionManager.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/CollisionManager.cpp.s
.PHONY : src/CollisionManager.cpp.s

src/Core/Camera.o: src/Core/Camera.cpp.o

.PHONY : src/Core/Camera.o

# target to build an object file
src/Core/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Core/Camera.cpp.o
.PHONY : src/Core/Camera.cpp.o

src/Core/Camera.i: src/Core/Camera.cpp.i

.PHONY : src/Core/Camera.i

# target to preprocess a source file
src/Core/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Core/Camera.cpp.i
.PHONY : src/Core/Camera.cpp.i

src/Core/Camera.s: src/Core/Camera.cpp.s

.PHONY : src/Core/Camera.s

# target to generate assembly for a file
src/Core/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Core/Camera.cpp.s
.PHONY : src/Core/Camera.cpp.s

src/Core/Collision.o: src/Core/Collision.cpp.o

.PHONY : src/Core/Collision.o

# target to build an object file
src/Core/Collision.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Core/Collision.cpp.o
.PHONY : src/Core/Collision.cpp.o

src/Core/Collision.i: src/Core/Collision.cpp.i

.PHONY : src/Core/Collision.i

# target to preprocess a source file
src/Core/Collision.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Core/Collision.cpp.i
.PHONY : src/Core/Collision.cpp.i

src/Core/Collision.s: src/Core/Collision.cpp.s

.PHONY : src/Core/Collision.s

# target to generate assembly for a file
src/Core/Collision.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Core/Collision.cpp.s
.PHONY : src/Core/Collision.cpp.s

src/Core/Material.o: src/Core/Material.cpp.o

.PHONY : src/Core/Material.o

# target to build an object file
src/Core/Material.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Core/Material.cpp.o
.PHONY : src/Core/Material.cpp.o

src/Core/Material.i: src/Core/Material.cpp.i

.PHONY : src/Core/Material.i

# target to preprocess a source file
src/Core/Material.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Core/Material.cpp.i
.PHONY : src/Core/Material.cpp.i

src/Core/Material.s: src/Core/Material.cpp.s

.PHONY : src/Core/Material.s

# target to generate assembly for a file
src/Core/Material.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Core/Material.cpp.s
.PHONY : src/Core/Material.cpp.s

src/Core/Primitives.o: src/Core/Primitives.cpp.o

.PHONY : src/Core/Primitives.o

# target to build an object file
src/Core/Primitives.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Core/Primitives.cpp.o
.PHONY : src/Core/Primitives.cpp.o

src/Core/Primitives.i: src/Core/Primitives.cpp.i

.PHONY : src/Core/Primitives.i

# target to preprocess a source file
src/Core/Primitives.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Core/Primitives.cpp.i
.PHONY : src/Core/Primitives.cpp.i

src/Core/Primitives.s: src/Core/Primitives.cpp.s

.PHONY : src/Core/Primitives.s

# target to generate assembly for a file
src/Core/Primitives.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Core/Primitives.cpp.s
.PHONY : src/Core/Primitives.cpp.s

src/Core/Ray.o: src/Core/Ray.cpp.o

.PHONY : src/Core/Ray.o

# target to build an object file
src/Core/Ray.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Core/Ray.cpp.o
.PHONY : src/Core/Ray.cpp.o

src/Core/Ray.i: src/Core/Ray.cpp.i

.PHONY : src/Core/Ray.i

# target to preprocess a source file
src/Core/Ray.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Core/Ray.cpp.i
.PHONY : src/Core/Ray.cpp.i

src/Core/Ray.s: src/Core/Ray.cpp.s

.PHONY : src/Core/Ray.s

# target to generate assembly for a file
src/Core/Ray.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Core/Ray.cpp.s
.PHONY : src/Core/Ray.cpp.s

src/GUI/SceneDisplayer.o: src/GUI/SceneDisplayer.cpp.o

.PHONY : src/GUI/SceneDisplayer.o

# target to build an object file
src/GUI/SceneDisplayer.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/GUI/SceneDisplayer.cpp.o
.PHONY : src/GUI/SceneDisplayer.cpp.o

src/GUI/SceneDisplayer.i: src/GUI/SceneDisplayer.cpp.i

.PHONY : src/GUI/SceneDisplayer.i

# target to preprocess a source file
src/GUI/SceneDisplayer.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/GUI/SceneDisplayer.cpp.i
.PHONY : src/GUI/SceneDisplayer.cpp.i

src/GUI/SceneDisplayer.s: src/GUI/SceneDisplayer.cpp.s

.PHONY : src/GUI/SceneDisplayer.s

# target to generate assembly for a file
src/GUI/SceneDisplayer.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/GUI/SceneDisplayer.cpp.s
.PHONY : src/GUI/SceneDisplayer.cpp.s

src/GUI/WindowManager.o: src/GUI/WindowManager.cpp.o

.PHONY : src/GUI/WindowManager.o

# target to build an object file
src/GUI/WindowManager.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/GUI/WindowManager.cpp.o
.PHONY : src/GUI/WindowManager.cpp.o

src/GUI/WindowManager.i: src/GUI/WindowManager.cpp.i

.PHONY : src/GUI/WindowManager.i

# target to preprocess a source file
src/GUI/WindowManager.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/GUI/WindowManager.cpp.i
.PHONY : src/GUI/WindowManager.cpp.i

src/GUI/WindowManager.s: src/GUI/WindowManager.cpp.s

.PHONY : src/GUI/WindowManager.s

# target to generate assembly for a file
src/GUI/WindowManager.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/GUI/WindowManager.cpp.s
.PHONY : src/GUI/WindowManager.cpp.s

src/Lamp.o: src/Lamp.cpp.o

.PHONY : src/Lamp.o

# target to build an object file
src/Lamp.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Lamp.cpp.o
.PHONY : src/Lamp.cpp.o

src/Lamp.i: src/Lamp.cpp.i

.PHONY : src/Lamp.i

# target to preprocess a source file
src/Lamp.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Lamp.cpp.i
.PHONY : src/Lamp.cpp.i

src/Lamp.s: src/Lamp.cpp.s

.PHONY : src/Lamp.s

# target to generate assembly for a file
src/Lamp.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Lamp.cpp.s
.PHONY : src/Lamp.cpp.s

src/Object.o: src/Object.cpp.o

.PHONY : src/Object.o

# target to build an object file
src/Object.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Object.cpp.o
.PHONY : src/Object.cpp.o

src/Object.i: src/Object.cpp.i

.PHONY : src/Object.i

# target to preprocess a source file
src/Object.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Object.cpp.i
.PHONY : src/Object.cpp.i

src/Object.s: src/Object.cpp.s

.PHONY : src/Object.s

# target to generate assembly for a file
src/Object.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Object.cpp.s
.PHONY : src/Object.cpp.s

src/RaytracerEngine.o: src/RaytracerEngine.cpp.o

.PHONY : src/RaytracerEngine.o

# target to build an object file
src/RaytracerEngine.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/RaytracerEngine.cpp.o
.PHONY : src/RaytracerEngine.cpp.o

src/RaytracerEngine.i: src/RaytracerEngine.cpp.i

.PHONY : src/RaytracerEngine.i

# target to preprocess a source file
src/RaytracerEngine.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/RaytracerEngine.cpp.i
.PHONY : src/RaytracerEngine.cpp.i

src/RaytracerEngine.s: src/RaytracerEngine.cpp.s

.PHONY : src/RaytracerEngine.s

# target to generate assembly for a file
src/RaytracerEngine.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/RaytracerEngine.cpp.s
.PHONY : src/RaytracerEngine.cpp.s

src/Scene.o: src/Scene.cpp.o

.PHONY : src/Scene.o

# target to build an object file
src/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Scene.cpp.o
.PHONY : src/Scene.cpp.o

src/Scene.i: src/Scene.cpp.i

.PHONY : src/Scene.i

# target to preprocess a source file
src/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Scene.cpp.i
.PHONY : src/Scene.cpp.i

src/Scene.s: src/Scene.cpp.s

.PHONY : src/Scene.s

# target to generate assembly for a file
src/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Scene.cpp.s
.PHONY : src/Scene.cpp.s

src/Shapes/Plane.o: src/Shapes/Plane.cpp.o

.PHONY : src/Shapes/Plane.o

# target to build an object file
src/Shapes/Plane.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Shapes/Plane.cpp.o
.PHONY : src/Shapes/Plane.cpp.o

src/Shapes/Plane.i: src/Shapes/Plane.cpp.i

.PHONY : src/Shapes/Plane.i

# target to preprocess a source file
src/Shapes/Plane.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Shapes/Plane.cpp.i
.PHONY : src/Shapes/Plane.cpp.i

src/Shapes/Plane.s: src/Shapes/Plane.cpp.s

.PHONY : src/Shapes/Plane.s

# target to generate assembly for a file
src/Shapes/Plane.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Shapes/Plane.cpp.s
.PHONY : src/Shapes/Plane.cpp.s

src/Shapes/Sphere.o: src/Shapes/Sphere.cpp.o

.PHONY : src/Shapes/Sphere.o

# target to build an object file
src/Shapes/Sphere.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Shapes/Sphere.cpp.o
.PHONY : src/Shapes/Sphere.cpp.o

src/Shapes/Sphere.i: src/Shapes/Sphere.cpp.i

.PHONY : src/Shapes/Sphere.i

# target to preprocess a source file
src/Shapes/Sphere.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Shapes/Sphere.cpp.i
.PHONY : src/Shapes/Sphere.cpp.i

src/Shapes/Sphere.s: src/Shapes/Sphere.cpp.s

.PHONY : src/Shapes/Sphere.s

# target to generate assembly for a file
src/Shapes/Sphere.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Shapes/Sphere.cpp.s
.PHONY : src/Shapes/Sphere.cpp.s

src/Shapes/Triangle.o: src/Shapes/Triangle.cpp.o

.PHONY : src/Shapes/Triangle.o

# target to build an object file
src/Shapes/Triangle.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Shapes/Triangle.cpp.o
.PHONY : src/Shapes/Triangle.cpp.o

src/Shapes/Triangle.i: src/Shapes/Triangle.cpp.i

.PHONY : src/Shapes/Triangle.i

# target to preprocess a source file
src/Shapes/Triangle.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Shapes/Triangle.cpp.i
.PHONY : src/Shapes/Triangle.cpp.i

src/Shapes/Triangle.s: src/Shapes/Triangle.cpp.s

.PHONY : src/Shapes/Triangle.s

# target to generate assembly for a file
src/Shapes/Triangle.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Shapes/Triangle.cpp.s
.PHONY : src/Shapes/Triangle.cpp.s

src/Tools/Color.o: src/Tools/Color.cpp.o

.PHONY : src/Tools/Color.o

# target to build an object file
src/Tools/Color.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Tools/Color.cpp.o
.PHONY : src/Tools/Color.cpp.o

src/Tools/Color.i: src/Tools/Color.cpp.i

.PHONY : src/Tools/Color.i

# target to preprocess a source file
src/Tools/Color.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Tools/Color.cpp.i
.PHONY : src/Tools/Color.cpp.i

src/Tools/Color.s: src/Tools/Color.cpp.s

.PHONY : src/Tools/Color.s

# target to generate assembly for a file
src/Tools/Color.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Tools/Color.cpp.s
.PHONY : src/Tools/Color.cpp.s

src/Tools/Debug.o: src/Tools/Debug.cpp.o

.PHONY : src/Tools/Debug.o

# target to build an object file
src/Tools/Debug.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Tools/Debug.cpp.o
.PHONY : src/Tools/Debug.cpp.o

src/Tools/Debug.i: src/Tools/Debug.cpp.i

.PHONY : src/Tools/Debug.i

# target to preprocess a source file
src/Tools/Debug.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Tools/Debug.cpp.i
.PHONY : src/Tools/Debug.cpp.i

src/Tools/Debug.s: src/Tools/Debug.cpp.s

.PHONY : src/Tools/Debug.s

# target to generate assembly for a file
src/Tools/Debug.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Tools/Debug.cpp.s
.PHONY : src/Tools/Debug.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/tests/test1.o: src/tests/test1.cpp.o

.PHONY : src/tests/test1.o

# target to build an object file
src/tests/test1.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/tests/test1.cpp.o
.PHONY : src/tests/test1.cpp.o

src/tests/test1.i: src/tests/test1.cpp.i

.PHONY : src/tests/test1.i

# target to preprocess a source file
src/tests/test1.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/tests/test1.cpp.i
.PHONY : src/tests/test1.cpp.i

src/tests/test1.s: src/tests/test1.cpp.s

.PHONY : src/tests/test1.s

# target to generate assembly for a file
src/tests/test1.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/tests/test1.cpp.s
.PHONY : src/tests/test1.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Raytracer"
	@echo "... src/CollisionManager.o"
	@echo "... src/CollisionManager.i"
	@echo "... src/CollisionManager.s"
	@echo "... src/Core/Camera.o"
	@echo "... src/Core/Camera.i"
	@echo "... src/Core/Camera.s"
	@echo "... src/Core/Collision.o"
	@echo "... src/Core/Collision.i"
	@echo "... src/Core/Collision.s"
	@echo "... src/Core/Material.o"
	@echo "... src/Core/Material.i"
	@echo "... src/Core/Material.s"
	@echo "... src/Core/Primitives.o"
	@echo "... src/Core/Primitives.i"
	@echo "... src/Core/Primitives.s"
	@echo "... src/Core/Ray.o"
	@echo "... src/Core/Ray.i"
	@echo "... src/Core/Ray.s"
	@echo "... src/GUI/SceneDisplayer.o"
	@echo "... src/GUI/SceneDisplayer.i"
	@echo "... src/GUI/SceneDisplayer.s"
	@echo "... src/GUI/WindowManager.o"
	@echo "... src/GUI/WindowManager.i"
	@echo "... src/GUI/WindowManager.s"
	@echo "... src/Lamp.o"
	@echo "... src/Lamp.i"
	@echo "... src/Lamp.s"
	@echo "... src/Object.o"
	@echo "... src/Object.i"
	@echo "... src/Object.s"
	@echo "... src/RaytracerEngine.o"
	@echo "... src/RaytracerEngine.i"
	@echo "... src/RaytracerEngine.s"
	@echo "... src/Scene.o"
	@echo "... src/Scene.i"
	@echo "... src/Scene.s"
	@echo "... src/Shapes/Plane.o"
	@echo "... src/Shapes/Plane.i"
	@echo "... src/Shapes/Plane.s"
	@echo "... src/Shapes/Sphere.o"
	@echo "... src/Shapes/Sphere.i"
	@echo "... src/Shapes/Sphere.s"
	@echo "... src/Shapes/Triangle.o"
	@echo "... src/Shapes/Triangle.i"
	@echo "... src/Shapes/Triangle.s"
	@echo "... src/Tools/Color.o"
	@echo "... src/Tools/Color.i"
	@echo "... src/Tools/Color.s"
	@echo "... src/Tools/Debug.o"
	@echo "... src/Tools/Debug.i"
	@echo "... src/Tools/Debug.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/tests/test1.o"
	@echo "... src/tests/test1.i"
	@echo "... src/tests/test1.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

