# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/media/guillaume/Data/Guillaume Coiffier/Documents/C++/Raytracer"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/media/guillaume/Data/Guillaume Coiffier/Documents/C++/Raytracer"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/guillaume/Data/Guillaume Coiffier/Documents/C++/Raytracer/CMakeFiles" "/media/guillaume/Data/Guillaume Coiffier/Documents/C++/Raytracer/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/guillaume/Data/Guillaume Coiffier/Documents/C++/Raytracer/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Raytracer

# Build rule for target.
Raytracer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Raytracer
.PHONY : Raytracer

# fast build rule for target.
Raytracer/fast:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/build
.PHONY : Raytracer/fast

src/Camera.o: src/Camera.cpp.o

.PHONY : src/Camera.o

# target to build an object file
src/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Camera.cpp.o
.PHONY : src/Camera.cpp.o

src/Camera.i: src/Camera.cpp.i

.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s

.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/Collection.o: src/Collection.cpp.o

.PHONY : src/Collection.o

# target to build an object file
src/Collection.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Collection.cpp.o
.PHONY : src/Collection.cpp.o

src/Collection.i: src/Collection.cpp.i

.PHONY : src/Collection.i

# target to preprocess a source file
src/Collection.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Collection.cpp.i
.PHONY : src/Collection.cpp.i

src/Collection.s: src/Collection.cpp.s

.PHONY : src/Collection.s

# target to generate assembly for a file
src/Collection.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Collection.cpp.s
.PHONY : src/Collection.cpp.s

src/Plane.o: src/Plane.cpp.o

.PHONY : src/Plane.o

# target to build an object file
src/Plane.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Plane.cpp.o
.PHONY : src/Plane.cpp.o

src/Plane.i: src/Plane.cpp.i

.PHONY : src/Plane.i

# target to preprocess a source file
src/Plane.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Plane.cpp.i
.PHONY : src/Plane.cpp.i

src/Plane.s: src/Plane.cpp.s

.PHONY : src/Plane.s

# target to generate assembly for a file
src/Plane.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Plane.cpp.s
.PHONY : src/Plane.cpp.s

src/Primitives.o: src/Primitives.cpp.o

.PHONY : src/Primitives.o

# target to build an object file
src/Primitives.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Primitives.cpp.o
.PHONY : src/Primitives.cpp.o

src/Primitives.i: src/Primitives.cpp.i

.PHONY : src/Primitives.i

# target to preprocess a source file
src/Primitives.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Primitives.cpp.i
.PHONY : src/Primitives.cpp.i

src/Primitives.s: src/Primitives.cpp.s

.PHONY : src/Primitives.s

# target to generate assembly for a file
src/Primitives.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Primitives.cpp.s
.PHONY : src/Primitives.cpp.s

src/Ray.o: src/Ray.cpp.o

.PHONY : src/Ray.o

# target to build an object file
src/Ray.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Ray.cpp.o
.PHONY : src/Ray.cpp.o

src/Ray.i: src/Ray.cpp.i

.PHONY : src/Ray.i

# target to preprocess a source file
src/Ray.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Ray.cpp.i
.PHONY : src/Ray.cpp.i

src/Ray.s: src/Ray.cpp.s

.PHONY : src/Ray.s

# target to generate assembly for a file
src/Ray.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Ray.cpp.s
.PHONY : src/Ray.cpp.s

src/RaytracerEngine.o: src/RaytracerEngine.cpp.o

.PHONY : src/RaytracerEngine.o

# target to build an object file
src/RaytracerEngine.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/RaytracerEngine.cpp.o
.PHONY : src/RaytracerEngine.cpp.o

src/RaytracerEngine.i: src/RaytracerEngine.cpp.i

.PHONY : src/RaytracerEngine.i

# target to preprocess a source file
src/RaytracerEngine.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/RaytracerEngine.cpp.i
.PHONY : src/RaytracerEngine.cpp.i

src/RaytracerEngine.s: src/RaytracerEngine.cpp.s

.PHONY : src/RaytracerEngine.s

# target to generate assembly for a file
src/RaytracerEngine.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/RaytracerEngine.cpp.s
.PHONY : src/RaytracerEngine.cpp.s

src/SceneDisplayer.o: src/SceneDisplayer.cpp.o

.PHONY : src/SceneDisplayer.o

# target to build an object file
src/SceneDisplayer.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/SceneDisplayer.cpp.o
.PHONY : src/SceneDisplayer.cpp.o

src/SceneDisplayer.i: src/SceneDisplayer.cpp.i

.PHONY : src/SceneDisplayer.i

# target to preprocess a source file
src/SceneDisplayer.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/SceneDisplayer.cpp.i
.PHONY : src/SceneDisplayer.cpp.i

src/SceneDisplayer.s: src/SceneDisplayer.cpp.s

.PHONY : src/SceneDisplayer.s

# target to generate assembly for a file
src/SceneDisplayer.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/SceneDisplayer.cpp.s
.PHONY : src/SceneDisplayer.cpp.s

src/ShapeManager.o: src/ShapeManager.cpp.o

.PHONY : src/ShapeManager.o

# target to build an object file
src/ShapeManager.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/ShapeManager.cpp.o
.PHONY : src/ShapeManager.cpp.o

src/ShapeManager.i: src/ShapeManager.cpp.i

.PHONY : src/ShapeManager.i

# target to preprocess a source file
src/ShapeManager.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/ShapeManager.cpp.i
.PHONY : src/ShapeManager.cpp.i

src/ShapeManager.s: src/ShapeManager.cpp.s

.PHONY : src/ShapeManager.s

# target to generate assembly for a file
src/ShapeManager.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/ShapeManager.cpp.s
.PHONY : src/ShapeManager.cpp.s

src/Sphere.o: src/Sphere.cpp.o

.PHONY : src/Sphere.o

# target to build an object file
src/Sphere.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Sphere.cpp.o
.PHONY : src/Sphere.cpp.o

src/Sphere.i: src/Sphere.cpp.i

.PHONY : src/Sphere.i

# target to preprocess a source file
src/Sphere.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Sphere.cpp.i
.PHONY : src/Sphere.cpp.i

src/Sphere.s: src/Sphere.cpp.s

.PHONY : src/Sphere.s

# target to generate assembly for a file
src/Sphere.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Sphere.cpp.s
.PHONY : src/Sphere.cpp.s

src/Triangle.o: src/Triangle.cpp.o

.PHONY : src/Triangle.o

# target to build an object file
src/Triangle.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Triangle.cpp.o
.PHONY : src/Triangle.cpp.o

src/Triangle.i: src/Triangle.cpp.i

.PHONY : src/Triangle.i

# target to preprocess a source file
src/Triangle.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Triangle.cpp.i
.PHONY : src/Triangle.cpp.i

src/Triangle.s: src/Triangle.cpp.s

.PHONY : src/Triangle.s

# target to generate assembly for a file
src/Triangle.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Triangle.cpp.s
.PHONY : src/Triangle.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Raytracer"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/Collection.o"
	@echo "... src/Collection.i"
	@echo "... src/Collection.s"
	@echo "... src/Plane.o"
	@echo "... src/Plane.i"
	@echo "... src/Plane.s"
	@echo "... src/Primitives.o"
	@echo "... src/Primitives.i"
	@echo "... src/Primitives.s"
	@echo "... src/Ray.o"
	@echo "... src/Ray.i"
	@echo "... src/Ray.s"
	@echo "... src/RaytracerEngine.o"
	@echo "... src/RaytracerEngine.i"
	@echo "... src/RaytracerEngine.s"
	@echo "... src/SceneDisplayer.o"
	@echo "... src/SceneDisplayer.i"
	@echo "... src/SceneDisplayer.s"
	@echo "... src/ShapeManager.o"
	@echo "... src/ShapeManager.i"
	@echo "... src/ShapeManager.s"
	@echo "... src/Sphere.o"
	@echo "... src/Sphere.i"
	@echo "... src/Sphere.s"
	@echo "... src/Triangle.o"
	@echo "... src/Triangle.i"
	@echo "... src/Triangle.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

